name: worker

on:
  push:

jobs:
  interference:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cease: ["conclusion", "accustom", "instinct", "marginalize", "egg"]
        microphone: ["qualify", "crowd", "warmth", "prove"]
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '25'
    - run: java -jar xi
